In [1]:
import pandas as pd
import numpy as np

In [2]:
# Dataset description:
# https://www.opensecrets.org/resources/datadictionary/Data%20Dictionary%20Candidates%20Data.htm
columns_campfin22_cands22 = ['cycle', 'feccandid', 'cid', 'firstlastp', 'party', 'distidrunfor', 
                    'distidcurr', 'currcand', 'cyclecand', 'crpico', 'recipcode', 
                    'nopacs']
columns_campfin22_cands22 = dict(enumerate(columns_campfin22_cands22))

In [3]:
df = pd.read_csv('../../data/open_secrets/CampaignFin22/cands22.csv', on_bad_lines='skip', sep=',', header=None, na_values=['N/A', 'NA'])
df = df.rename(columns=columns_campfin22_cands22)

In [4]:
# Get rid of the pipes on both sides of the data.
df = df.map(lambda x: x.replace('|', '') if type(x) == str else x)

# Other cleanup.
df['cycle'] = df['cycle'].apply(lambda x: int(x))

In [5]:
pd.options.display.max_columns = None
df

,cycle,feccandid,cid,firstlastp,party,distidrunfor,distidcurr,currcand,cyclecand,crpico,recipcode,nopacs
0,2022,H0AK00105,N00039029,Thomas Lamb (3),3,AK01,,,,,3N,
1,2022,H0AL01055,N00044245,Jerry Carl (R),R,AL01,AL01,Y,Y,I,RW,
2,2022,H0AL01063,N00044288,Wes Lambert (R),R,AL01,,,,,RN,
3,2022,H0AL01097,N00044750,James Averhart (D),D,AL01,,,,,DN,
4,2022,H0AL02087,N00030768,Martha Roby (R),R,AL02,,,,,RN,
...,...,...,...,...,...,...,...,...,...,...,...,...
8910,2022,S8WI00224,N00041929,Leah Vukmir (R),R,WIS1,,,,,RN,
8911,2022,S8WV00119,N00041293,Paula Jean Swearengin (D),D,WVS2,,,,,DN,
8912,2022,S8WV00127,N00035531,Evan Jenkins (R),R,WVS1,,,,,RN,
8913,2022,S8WV00135,N00041474,Bo Copley (R),R,WVS1,,,,,RN,
8914,2022,S8WV00143,N00012642,Patrick Morrisey (R),R,WVS1,,,,,RN,

In [11]:
# See crp_ids.ipynb where candidate names, their party, and their district are all associated with a cid and a feccandid.

In [6]:
df_cand = df[df['feccandid'] == 'H8IN07184'] # good if we analyze only ONE cycle. This field is more present across datasets.
df_cand

,cycle,feccandid,cid,firstlastp,party,distidrunfor,distidcurr,currcand,cyclecand,crpico,recipcode,nopacs
5621,2022,H8IN07184,N00029513,Andre Carson (D),D,IN07,IN07,Y,Y,I,DW,

In [7]:
df_cand2 = df[df['cid'] == 'N00029513'] # this is the non-mutable candidate id, but there are other tables that use "cid" for other things.
df_cand2

,cycle,feccandid,cid,firstlastp,party,distidrunfor,distidcurr,currcand,cyclecand,crpico,recipcode,nopacs
5621,2022,H8IN07184,N00029513,Andre Carson (D),D,IN07,IN07,Y,Y,I,DW,

In [8]:
df_cand3 = df[df['cid'] == 'N00036203']
df_cand3

,cycle,feccandid,cid,firstlastp,party,distidrunfor,distidcurr,currcand,cyclecand,crpico,recipcode,nopacs
8647,2022,S4NJ00292,N00036203,Brian Goldberg (R),R,NJS1,,,,,RN,