In [1]:
import pandas as pd
import numpy as np

In [2]:
# Blank excel column
columns_indivs = ['cycle', 'fectransid', 'contribid', 'contrib', 'recipid', 'orgname',
                   'ultorg', 'realcode', 'date', 'amount', 'street', 'city', 'state', 'zip',
                   'recipcode', 'type', 'cmteid', 'otherid', 'gender', 'microfilm',
                   'occupation', 'employer', 'source']
columns_indivs = dict(enumerate(columns_indivs))

In [3]:
df = pd.read_csv('../../data/open_secrets/indivs_N00000362_20.csv', header=None, skiprows=1)
df = df.rename(columns=columns_indivs)

In [4]:
# Get rid of the pipes on both sides of the data.
df = df.map(lambda x: x.replace('|', '') if type(x) == str else x)

# Other cleanup.
df['cycle'] = df['cycle'].apply(lambda x: int(x))
df['fectransid'] = df['fectransid'].apply(lambda x: int(x))
df['date'] = df['date'].apply(lambda x: x[:10])
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
df['amount'] = df['amount'].apply(lambda x: int(x))
df['zip'] = df['zip'].apply(lambda x: int(x))

In [5]:
pd.options.display.max_columns = None
df

,cycle,fectransid,contribid,contrib,recipid,orgname,ultorg,realcode,date,amount,street,city,state,zip,recipcode,type,cmteid,otherid,gender,microfilm,occupation,employer,source
0,2020,4032420201713158048,i3003425569,"SPERLING, MICHAEL",N00000362,[24T Contribution],NaN,Z9500,2020-01-17,2000,NaN,BOSTON,MA,2116,DW,24T,C00401224,C00238907,M,202002219201582298,INVESTOR,BAUPOST,Rept
1,2020,4040220201721116424,h1001289155,"CHOQUETTE, PAUL",N00000362,[24T Contribution],NaN,Z9500,2020-02-07,1500,NaN,WARWICK,RI,2818,DW,24T,C00401224,C00238907,M,202003209210675429,VICE CHAIRMAN,"GILBANE, INC.",Rept
2,2020,4040220201720086172,m0001319780,"BRAMZON, DAVID",N00000362,[24T Contribution],NaN,Z9500,2020-02-21,250,NaN,SAN DIEGO,CA,92101,DW,24T,C00401224,C00238907,M,202003209210502345,REAL ESTATE DEVELOPER,SELF,Rept
3,2020,4040220201724134365,c0070444420,"GIANCOLA, LOUIS",N00000362,[24T Contribution],NaN,Z9500,2020-02-12,1000,NaN,PROVIDENCE,RI,2906,DW,24T,C00401224,C00238907,M,202003209211156076,NOT EMPLOYED,NOT EMPLOYED,Rept
4,2020,4040220201727072484,p0005312808,"KORNFELD, RICHARD",N00000362,[24T Contribution],NaN,Z9500,2020-02-14,1000,NaN,LA JOLLA,CA,92037,DW,24T,C00401224,C00238907,M,202003209211657449,CEO,"KITU SYSTEMS, INC",Rept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2306,2020,4051420201752282628,j1002280440,"STURTEVANT, MARY",N00000362,[24T Contribution],NaN,Z9500,2020-03-12,2000,NaN,ARLINGTON,VA,22207,DW,24T,C00401224,C00238907,F,202004219230182139,VICE PRESIDENT,LOCKHEED MARTIN,Rept
2307,2020,4051420201752604217,e1110791881,"TING, DAVID",N00000362,[24T Contribution],NaN,Z9500,2020-03-10,1000,NaN,BOSTON,MA,2116,DW,24T,C00401224,C00238907,M,202004219230238335,ADMINISTRATION,MUGAR ENTERPRISES INC.,Rept
2308,2020,4030220201213570420,h1001143082,"MILLER, MYRON",N00000362,[24T Contribution],NaN,Z9500,2019-10-08,500,NaN,DENVER,CO,80222,DW,24T,C00401224,C00238907,M,202001299182307009,NaN,NaN,Rept
2309,2020,4020320212016074888,n0001155310,"ALMON, DAWN",N00000362,[24T Contribution],NaN,Z9500,2020-10-13,25,NaN,PALM COAST,FL,32137,DW,24T,C00401224,C00238907,F,202012179387416303,NOT EMPLOYED,NOT EMPLOYED,Rept
2310,2020,4030220201215122929,j1002510624,"VAN GEERTRUYDEN, YANN",N00000362,[24T Contribution],NaN,Z9500,2019-10-09,1400,NaN,WASHINGTON,DC,20006,DW,24T,C00401224,C00238907,U,202001299174998026,ATTORNEY,GOULSTON AND STORRS,Rept