# SI 608 Project #
#### Sai Avula, Nicholas Ketchum | Fall 2025 ####
This project explores potential effects of money in politics that are passed between various political action committees that propose and sponsor industry-specific legislation.

### Initialize
Init file contains helper functions used throughout the project.

In [7]:
%run modules/init.ipynb

Initializing project...
pandas is already installed.
matplotlib is already installed.
networkx is already installed.
numpy is already installed.
...initialization complete.

#### Load datasets ####

This module provides a single function for all of the *contribution* data from OpenSecrets.

In [9]:
%run modules/data.ipynb

Loading data module...
...data module loaded.

In [10]:
# Dataset description:
# https://www.opensecrets.org/resources/datadictionary/Data%20Dictionary%20for%20Individual%20Contribution%20Data.htm
columns_indivs22 = ['cycle', 'fectransid', 'contribid', 'contrib_last', 'contrib_first', 'recipid', 'orgname', 
                    'ultorg', 'realcode', 'date', 'amount', 'street', 'city', 'state',
                    'zip', 'recipcode', 'type', 'cmteid', 'otherid', 'gender', 'microfilm',
                    'occupation', 'employer', 'source']

# This dataset is huge, and crashes my computer. For now, limiting to 1000000 rows
# until a better way is found to trim off this dataset to only the last cycle or two
df_indivs22 = create_dataframe('../../data/open_secrets/CampaignFin22/indivs22.csv', columns_indivs22, nrows=1000000)

df_indivs22.head()

Creating dataframe...
dataframe created...

,cycle,fectransid,contribid,contrib_last,contrib_first,recipid,orgname,ultorg,realcode,date,amount,street,city,state,zip,recipcode,type,cmteid,otherid,gender,microfilm,occupation,employer,source,active,fecrecno,foreign
0,2022,4061520221505841534,r0014256510,DILLARD,DANIEL,C00000935,[24T Contribution],,Z9500,2021-08-29,35,,HIDALGO,TX,78557,DP,24T,C00401224,C00000935,M,202205149504021121,NOT EMPLOYED,NOT EMPLOYED,Rept,None,None,None
1,2022,4061520221505841535,r0015503614,WHITE,SCOTTO,C00633404,[24T Contribution],,Z9500,2021-08-29,15,,YONKERS,NY,10701,PI,24T,C00401224,C00633404,M,202205149507911003,NOT EMPLOYED,NOT EMPLOYED,Rept,None,None,None
2,2022,4061520221505841536,p0003861308,DOMINGUEZ,SALLIE,C00632398,[24T Contribution],,Z9500,2021-08-29,10,,CAMPBELL,CA,95011,PI,24T,C00401224,C00632398,F,202205149504046504,HEALTHCARE,MCDONALD FAMILY DENTAL,Rept,None,None,None
3,2022,4061520221505841543,p0003689535,BRADLEY,JANNETTE,C00678839,[24T Contribution],,Z9500,2021-08-29,26,,OAK LAWN,IL,60453,PI,24T,C00401224,C00678839,F,202205149503347140,LIBRARIAN,MEDICAL CENTER,Rept,None,None,None
4,2022,4061520221505841545,q0002181378,BHATT,TANYA,C00580068,[24T Contribution],,Z9500,2021-08-29,50,,MIAMI BEACH,FL,33141,PI,24T,C00401224,C00580068,F,202205149503225635,MKTG,FRYE FINANCIAL,Rept,None,None,None

In [11]:
# Dataset description:
# https://www.opensecrets.org/resources/datadictionary/Data%20Dictionary%20for%20Cmtes.htm
columns_cmtes22 = ['cycle', 'cmteid', 'pacshort', 'affiliate', 'ultorg', 'recipid', 
                    'recipcode', 'feccandid', 'party', 'primcode', 'source', 'sensitive',
                    'foreign', 'active']

df_cmtes22 = create_dataframe('../../data/open_secrets/CampaignFin22/cmtes22.csv', columns_cmtes22)

df_cmtes22.head()

Creating dataframe...
dataframe created...

,cycle,cmteid,pacshort,affiliate,ultorg,recipid,recipcode,feccandid,party,primcode,source,sensitive,foreign,active,fecrecno,fectransid
0,2022,C00000059,Hallmark Cards,NaN,Hallmark Cards,C00000059,PB,NaN,NaN,C1400,WAA21,Y,0,1,None,None
1,2022,C00000422,American Medical Assn,American Medical Assn,American Medical Assn,C00000422,PB,NaN,NaN,H1100,WAA21,n,0,1,None,None
2,2022,C00000489,Teamsters Local 886,Teamsters Union,Teamsters Union,C00000489,PL,NaN,,LT300,WAA21,n,0,1,None,None
3,2022,C00000547,KANSAS MEDICAL SOCIETY POLITICAL ACTION COMMIT...,NaN,NaN,C00000547,NaN,NaN,U,NaN,NaN,NaN,0,0,None,None
4,2022,C00000729,American Dental Assn,American Dental Assn,American Dental Assn,C00000729,PB,NaN,NaN,H1400,WAA21,n,0,1,None,None

In [12]:
# Dataset description:
# https://www.opensecrets.org/resources/datadictionary/Data%20Dictionary%20527%20Cmtes.htm
columns_cmtes527 = ['cycle', 'rpt', 'ein', 'crp527name', 'affiliate', 'ultorg', 
                    'recipcode', 'cmteid', 'cid', 'eccmteid', 'party', 
                    'primcode', 'source', 'ffreq', 'ctype', 'csource', 'viewpt',
                    'comments', 'state']

df_cmtes527 = create_dataframe('../../data/open_secrets/527/cmtes527.csv', columns_cmtes527)

df_cmtes527.head()

Creating dataframe...
dataframe created...

,cycle,rpt,ein,crp527name,affiliate,ultorg,recipcode,cmteid,cid,eccmteid,party,primcode,source,ffreq,ctype,csource,viewpt,comments,state,active,fecrecno,fectransid,foreign
0,2002,Q302,861006189,American Electronics Assn,,American Electronics Assn,PB,,,,NaN,C5000,WebPN,Q,F,NaN,N,,AZ,None,None,None,None
1,2008,Q308,262108560,California 2008 GOP Delegation Corporate,,California 2008 GOP Delegation,RP,,,,R,Z5100,Name,Q,F,,C,,CA,None,None,None,None
2,2000,Q400,912101097,Alabama League of Environmental Action,,Alabama League of Environmental Action,PI,,,,NaN,JE300,Name,Q,S,Name,L,,AL,None,None,None,None
3,2012,Q412,522257109,International Brotherhood of Electrical Workers,,International Brotherhood of Electrical Workers,PL,C00027342,,,,LC150,PAC,Q,F,Name,L,,DC,None,None,None,None
4,2008,Q407,900049259,Pacific Northwest Regional Council of Carpenters,,Carpenters & Joiners Union,PL,C00001016,,C70004205,,LB100,PAC,Q,F,Expen,L,,WA,None,None,None,None

In [13]:
# Dataset description:
# https://www.opensecrets.org/resources/datadictionary/Data%20Dictionary%20Candidates%20Data.htm
columns_cands22 = ['cycle', 'rpt', 'ein', 'crp527name', 'affiliate', 'ultorg', 
                    'recipcode', 'cmteid', 'cid', 'eccmteid', 'party', 
                    'primcode', 'source', 'ffreq', 'ctype', 'csource', 'viewpt',
                    'comments', 'state']

df_cands22 = create_dataframe('../../data/open_secrets/CampaignFin22/cands22.csv', columns_cands22)

df_cands22.head()

Creating dataframe...
dataframe created...

,cycle,rpt,ein,crp527name,affiliate,ultorg,recipcode,cmteid,cid,eccmteid,party,primcode,active,fecrecno,fectransid,foreign
0,2022,H0AK00105,N00039029,Thomas Lamb (3),3,AK01,,,,,3N,,None,None,None,None
1,2022,H0AL01055,N00044245,Jerry Carl (R),R,AL01,AL01,Y,Y,I,RW,,None,None,None,None
2,2022,H0AL01063,N00044288,Wes Lambert (R),R,AL01,,,,,RN,,None,None,None,None
3,2022,H0AL01097,N00044750,James Averhart (D),D,AL01,,,,,DN,,None,None,None,None
4,2022,H0AL02087,N00030768,Martha Roby (R),R,AL02,,,,,RN,,None,None,None,None

In [14]:
# Dataset description:
# https://www.opensecrets.org/resources/datadictionary/Data%20Dictionary%20PAC%20to%20PAC%20Data.htm
columns_pac_other22 = ['cycle', 'fecrecno', 'filerid', 'donorcmte', 'contriblendtrans', 'city', 'state', 
                            'zip', 'fecoccemp', 'primcode', 'date', 'amount', 'recipid', 'party', 'otherid',
                            'recipcode', 'recipprimcode', 'amend', 'report', 'pg', 'microfilm', 'type',
                            'realcode', 'source']

df_pac_other22 = create_dataframe('../../data/open_secrets/CampaignFin22/pac_other22.csv', columns_pac_other22)

df_pac_other22.head()

Creating dataframe...
dataframe created...

,cycle,fecrecno,filerid,donorcmte,contriblendtrans,city,state,zip,fecoccemp,primcode,date,amount,recipid,party,otherid,recipcode,recipprimcode,amend,report,pg,microfilm,type,realcode,source,active,fectransid,foreign
0,2022,1011320230265253021,C00032979,Teamsters Union,BOHANNAN VICTORY FUND,IOWA CITY,IA,52245,NaN,LT300,2022-11-15,-1000.0,C00811059,D,C00811059,DP,Z4200,A,30G,P,202212089550408190,24K,LT300,PAC,None,None,None
1,2022,1011320230265254787,C00032979,Teamsters Union,WARNOCK VICTORY FUND,WASHINGTON,DC,20003,NaN,LT300,2022-11-22,15000.0,C00740597,D,C00740597,DP,Z4200,A,30G,P,202212089550408210,24K,LT300,PAC,None,None,None
2,2022,1011320230265254797,C00032979,Teamsters Union,BLUE POWER PAC,COLLINSWOOD,NJ,08108,NaN,LT300,2022-11-03,5000.0,C00575894,D,C00575894,PI,J2100,A,30G,P,202212089550408207,24K,LT300,PAC,None,None,None
3,2022,1011320230265254799,C00032979,Teamsters Union,COMMONWEALTH PAC,MERRIFIELD,VA,22116,NaN,LT300,2022-11-03,5000.0,C00498931,D,C00498931,PI,J2100,A,30G,P,202212089550408208,24K,LT300,PAC,None,None,None
4,2022,1011320230265254826,C00032979,Teamsters Union,RHODE ISLAND DEMOCRATIC STATE CMTE,PROVIDENCE,RI,92940,NaN,LT300,2022-11-03,5000.0,C00136200,D,C00136200,DP,Z5200,A,30G,P,202212089550408209,24K,LT300,PAC,None,None,None

In [15]:
%run modules/plot_contrib.ipynb

In [16]:
%run modules/plot_contrib_pacs22.ipynb

In [ ]:
G = make_plot_contrib_pacs22(df_pac_other22, df_cmtes22, nrows=7500)

In [ ]:
plot_contrib_details(G)

In [ ]:
# Use the graph to construct a party-neutral chart.

C = nx.community.greedy_modularity_communities(G)

color_map = {'D': 'blue', 'R': 'red', 'G': 'green', 'I': 'brown', 'X': 'gray'}
node_colors = {}

for community in C:
    for node in community:
        party = G.nodes[node].get('party', 'X')
        node_colors[node] = color_map.get(party, 'gray')

node_color_list = [node_colors.get(node, 'gray') for node in G.nodes]
plt.figure(figsize=(10, 10))
pos = nx.spring_layout(G, k=1, scale=2, iterations=200)
nx.draw(G, pos, node_color=node_color_list, with_labels=False, node_size=2, edge_color='gray', width=0.15, edgecolors='white')
plt.show()

In [ ]:
G_D = make_plot_contrib_pacs22(df_pac_other22, df_cmtes22, party='D', nrows=7500)

In [ ]:
G_R = make_plot_contrib_pacs22(df_pac_other22, df_cmtes22, party='R', nrows=7500)